f = open('curtis_table.txt')
content = f.readlines()
f.close()

untagged = []
tags = []

MAX_X = 34
MAX_UNEVEN_INPUT = 71


for line in content:
    l = line.rstrip(")\n").lstrip("((").split("#")
    stemfilt = l[0].rstrip(") ").split(' ')
    
    stem = int(stemfilt[0])
    filt = int(stemfilt[1])

    if len(l) == 3:
        ltag = l[1].lstrip('(').split(')')[0]
        rtag = l[2].lstrip('(').split(')')[0]
        tags.append((stem, filt, ltag, rtag))
    else:
        unt = l[1].lstrip('(').split(')')[0]
        untagged.append((stem, filt, unt))


def tag_to_name(n: str, x, y, af) -> str:
    original = n
    output = ""
    map = {
        "1 2 3 4 4 1 1 1": "h_1Pc_0",
        "1 1 2 4 3 3 3": "h_0^3e_0",
        "2 3 4 4 1 1 1": "Pc_0",
        "1 2 4 3 3 3": "h_1^2d_0",
        "2 2 4 3 3 3": "h_0^2e_0",
        "2 4 3 3 3": "h_1d_0",
        "4 4 1 1 1": "Ph_2",
        "1 1 2 4 1 1 1": "h_0^2Ph_2", 
        "2 2 4 1 1 1": "h_0Ph_2", 
        "1 2 4 1 1 1": "h_1Ph_1",
        "2 4 1 1 1": "Ph_1", 
        "5 1 2 3 3": "h_0d_0", 

        "1 2 3 3": "h_1c_0",
        "2 4 1 1": "P", 
        "6 2 3 3": "d_0", 
        "4 1 1 1": "h_0^3h_3", 

        "6 5 3": "h_0h_3^2", 
        "2 3 3": "c_0", 
        "3 3 3": "h_1^2h_3", 
        "5 1 1": "h_0^2h_3", 
        "1 1 1": "h_0^2h_2", 

        "5 3": "h_1h_3", 
        "6 1": "h_0h_3", 
        "2 1": "h_0h_2",   
        "4 5": "h_0f_0", 
        "3 6": "h_0e_0", 
        "3 3": "h_2^2", 
        "1 1": "h_1^2",  
        
        "7": "h_3", 
        "3": "h_2", 
        "1": "h_1",  
        "0": "h_0",  
    }

    while True:
        flag = False
        for [comp, ans] in map.items():
            if n.endswith(comp):
                output = output + ans
                n = n.rstrip(comp).rstrip()
                flag = True
                break
        if flag == False:
            print(original, "|", x, y, af)
            return 
        if n == "":
            break
    
    return output






gens = []
diffs = []
mults = []

gens.append("{\"name\":\"1(∞)\",\"x\":0,\"y\":0,\"adams_filtration\":0}")
for n in range(3, MAX_UNEVEN_INPUT, 4):
    y = n // 2
    a = "{\"name\":\"[" + str(y) + "]" "\", \"x\":" + str(y) + ", \"y\":" + str(y) +", \"adams_filtration\":1}"
    b = "{\"name\":\"2(∞)[" + str(y) + "]" "\", \"x\":" + str(y) + ", \"y\":" + str(y) +", \"adams_filtration\":2}"
    c = "{\"name\":\"1(∞)[" + str(y + 1) + "]" "\", \"x\":" + str(y+1) + ", \"y\":" + str(y+1) +", \"adams_filtration\":1}"
    
    d = "{\"from\":\"1(∞)[" + str(y + 1) + "]\", \"to\":\"2(∞)[" + str(y) + "]\", \"coeff\":0, \"d\":1}"

    gens.append(a)
    gens.append(b)
    gens.append(c)
    diffs.append(d)


# for [s, f, l] in untagged:
#     if s <= 12:
#         initial = l.split(' ', 1)[0]
#         sphere = int(initial)
#         if sphere < n:
#             t = tag_to_name(l)
#             if t == None:
#                 print(l, t)

# Stable generators
for n in range(3, MAX_UNEVEN_INPUT, 2):
    y = n // 2
    for [s, f, l] in untagged:
        if s+y <= MAX_X:
            initial = l.split(' ', 1)[0]
            sphere = int(initial)
            if sphere < n:
                a = "{\"name\":\"" + l + "[" + str(y) + "]" "\", \"x\":" + str(s + y) + ", \"y\":" + str(y) +", \"adams_filtration\":" + str(f + 1) + "}"
                gens.append(a)

# Unstable generators
for n in range(3, MAX_UNEVEN_INPUT, 2):
    y = n // 2
    for [s, f, l, r] in tags:
        if s+y <= MAX_X:
            initial = l.split(' ', 1)[0]
            initial_tag = r.split(' ', 1)[0]
            sphere = int(initial)
            tag_sphere = int(initial_tag)
            if sphere < n and n <= tag_sphere:
                a = "{\"name\":\"" + l + "[" + str(y) + "]" "\", \"x\":" + str(s + y) + ", \"y\":" + str(y) +", \"adams_filtration\":" + str(f + 1) + "}"
                gens.append(a)
        


# Differentials
for [s, f, l, r] in tags:
    if s <= MAX_X:
        rspl = r.split(" ", 1)
        f = "[" + rspl[0] + "]" 
        if len(rspl) == 2:
            f = rspl[1] + f

        lspl = l.split(" ", 1)
        t = "[" + lspl[0] + "]"
        if len(lspl) == 2:
            t = lspl[1] + t
        d_r = int(rspl[0]) - int(lspl[0])
        d = "{\"from\":\"" + f + "\", \"to\":\"" + t + "\", \"coeff\":0, \"d\":" + str(d_r) + "}"
        diffs.append(d)

        if s == MAX_X: 
            y = int(rspl[0])
            af = len(r.split(" "))
            a = "{\"name\":\"" + f + "\", \"x\":" + str(s + 1) + ", \"y\":" + str(y) +", \"adams_filtration\":" + str(af) + "}"
            gens.append(a)





pre = '// This file has been generated by curtis_to_data.py\n// Based on curtis tables of the AEHP sequence\nimport { SyntheticEHP } from "./types";\n\nexport const data: SyntheticEHP = {\n    "generators": [\n'
ds = '\n    ],\n    "differentials": [\n'
ms = '\n    ],\n    "multiplications": ['
post = '    ]\n}'

f = open('./site/src/algebraic_data.ts', '+w')
f.write(pre + ",\n".join(gens) + ds + ",\n".join(diffs) + ms + ",\n".join(mults) + post )
