import { Generators } from "../types";
import { getActiveData } from "./dataSource";

/**
 * Generator-name parsing.
 *
 * Generator names encode structural information in a compact textual form,
 * e.g. `"1 1[2]"`. The trailing `[n]` is the sphere the class lives on, and
 * the leading tokens describe how it is generated from a lower class. These
 * helpers translate between those naming conventions; they are pure string
 * manipulation and deliberately know nothing about pages or rendering.
 */

/**
 * The name of the class that *generates* `gen` — i.e. drop everything but the
 * first token and the sphere bracket. `"1 1[2]"` -> `"1[1]"`.
 */
export function generated_by_name(gen: Generators): string {
    const initial = gen.name.split("[")[0];
    const split_first = initial.split(" ");
    const end = "[" + String(split_first[0]) + "]";
    if (split_first.length == 1) {
        return end;
    }
    return split_first.slice(1).join(" ") + end;
}

/**
 * The "generating name": the sphere index moved to the front of the operation
 * tokens. `"1 1[2]"` -> `"2 1 1"`. Used to find the family a class belongs to.
 */
export function generating_name(gen: Generators): string {
    const [initial, last] = gen.name.split("[");
    const real_last = last.split("]")[0];
    if (initial == "") {
        return real_last;
    }
    return real_last + " " + initial;
}

function parseSphereFromName(name: string): number | undefined {
    const match = name.match(/\[(\d+)\]$/);
    return match ? parseInt(match[1], 10) : undefined;
}

/**
 * The induced name to display for `gen` when viewing the chart truncated at the
 * given `sphere`. `induced_name` is a list of `[fromSphere, name]` checkpoints;
 * we return the name in effect at `sphere`.
 */
export function get_induced_name(gen: Generators, sphere: number): string {
    const l = gen.induced_name ?? [[0, gen.name] as [number, string]];
    let id = 0;
    while (true) {
        if (id + 1 == l.length) return l[id][1];
        if (l[id + 1][0] > sphere) return l[id][1];
        id += 1;
    }
}

/**
 * The lifecycle of a class in terms of the sphere it is born on and the sphere
 * its algebraic class dies on. Prefers explicit `born`/`dies` fields, falling
 * back to the spheres recorded in `induced_name` or parsed from the name.
 */
export function getSphereLifecycleInfo(gen: Generators): { bornSphere: string; diesOnAlgebraicSphere: string } {
    const explicitBorn = (gen as any).born;
    const explicitDies = (gen as any).dies;

    if (explicitDies === null || explicitDies === undefined) {
        return {
            bornSphere: explicitBorn !== undefined ? String(explicitBorn) : "Unknown",
            diesOnAlgebraicSphere: "survives",
        };
    }

    const inducedSpheres = (gen.induced_name ?? [])
        .map(([sphere]) => sphere)
        .filter((sphere) => sphere > 0);

    const parsedSphere = parseSphereFromName(gen.name);
    const born = explicitBorn !== undefined
        ? explicitBorn
        : inducedSpheres.length > 0
        ? Math.min(...inducedSpheres)
        : parsedSphere;
    const maxPresent = explicitDies !== undefined
        ? explicitDies - 1
        : inducedSpheres.length > 0
        ? Math.max(...inducedSpheres)
        : parsedSphere;
    const dies = maxPresent !== undefined ? maxPresent + 1 : undefined;

    return {
        bornSphere: born !== undefined ? born.toString() : "Unknown",
        diesOnAlgebraicSphere: dies !== undefined ? dies.toString() : "Unknown",
    };
}

/**
 * All classes generated by the same family as `gen`, ordered by sphere index.
 * Found by matching `generating_name(gen)[<sphere>]` against the active data.
 */
export function generates(gen: Generators): Generators[] {
    const name = generating_name(gen);
    const activeData = getActiveData();
    if (!activeData) return [];

    const escapedName = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const re = new RegExp(`^${escapedName}\\[(\\d+)\\]$`);
    return activeData.generators
        .map((g) => {
            const match = re.exec(g.name);
            return match ? { g, idx: parseInt(match[1], 10) } : null;
        })
        .filter((entry): entry is { g: Generators; idx: number } => entry !== null)
        .sort((a, b) => a.idx - b.idx)
        .map((entry) => entry.g);
}
