use std::{fs::File, io::Write};

use crate::MAX_STEM;

pub fn write_typescript_file(
    output_path: &str,
    data: &crate::types::SyntheticSS,
) -> Result<(), std::io::Error> {
    let mut file = File::create(output_path)?;

    // Serialize generators to JSON strings
    let gens: Vec<String> = data.generators
        .iter()
        .map(|g| serde_json::to_string(g).unwrap())
        .collect();

    // Serialize differentials to JSON strings
    let diffs: Vec<String> = data.differentials
        .iter()
        .map(|d| serde_json::to_string(d).unwrap())
        .collect();

    // Serialize multiplications to JSON strings
    let mults: Vec<String> = data.multiplications
        .iter()
        .map(|m| serde_json::to_string(m).unwrap())
        .collect();

    let tau_mults: Vec<String> = data.tau_mults
        .iter()
        .map(|m| serde_json::to_string(m).unwrap())
        .collect();

    let pre = format!(
        "// This file has been generated by curtis.rs\n\
         // Based on curtis tables of the AEHP sequence\n\
         import {{ SyntheticEHP }} from \"./types\";\n\n\
         export const MAX_STEM = {};\n\n\
         export const data: SyntheticEHP = {{\n\
         \x20   \"generators\": [\n",
        MAX_STEM
    );

    let ds = "\n    ],\n    \"differentials\": [\n";
    let ms = "\n    ],\n    \"multiplications\": [\n";
    let ts = "\n    ],\n    \"tau_mults\": [\n";
    let post = "    ]\n}";

    file.write_all(pre.as_bytes())?;
    file.write_all(gens.join(",\n").as_bytes())?;
    file.write_all(ds.as_bytes())?;
    file.write_all(diffs.join(",\n").as_bytes())?;
    file.write_all(ms.as_bytes())?;
    file.write_all(mults.join(",\n").as_bytes())?;
    file.write_all(ts.as_bytes())?;
    file.write_all(tau_mults.join(",\n").as_bytes())?;
    file.write_all(post.as_bytes())?;

    Ok(())
}